client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Default:index }
client_addAskService:
    path:     /add
    defaults: { _controller: ClientBundle:AskService:add }
client_displayservice:
        path:     /displayservice
        defaults: { _controller: ClientBundle:AskService:display }
client_deleteservice:
            path:     /deleteAskService/{id}
            defaults: { _controller: ClientBundle:AskService:deleteAskService }
client_editeservice:
        path:     /editAskService/{id}
        defaults: { _controller: ClientBundle:AskService:editAskService }
client_showpaiement:
    path:     /showpaiement/{id}
    defaults: { _controller: ClientBundle:AskService:showpaiement }
client_paiement:
    path:     /paiement
    defaults: { _controller: ClientBundle:AskService:paiement }
detail_service:
        path:     /detailservice/{id}
        defaults: { _controller: ClientBundle:Default:afficheDetail }
        methods:  [GET, POST]
our_category:
    path:     /ourcategory
    defaults: { _controller: ClientBundle:AskService:OurCategory }
client_addPost:
    path:     /createPost
    defaults: { _controller: ClientBundle:Post:create }
client_forum:
    path:     /forum
    defaults: { _controller: ClientBundle:Post:list }
#client_deletePost:
#        path:     /deletePost/{id}
#        defaults: { _controller: ClientBundle:Post:deletePost }
#client_editPost:
#        path:     /editPost/{id}
#        defaults: { _controller: ClientBundle:Post:editPost }
client_deletePost:
    path:     /deletePost/{id}
    defaults: { _controller: ClientBundle:Post:deletePost }
client_editPost:
    path:     /editPost/{id}
    defaults: { _controller: ClientBundle:Post:editPost }
client_addComment:
    path:     /createComment/{id}
    defaults: { _controller: ClientBundle:Comment:create }
client_showComment:
    path:     /showComment/{id}
    defaults: { _controller: ClientBundle:Comment:list }
client_deleteComment:
    path:     /deleteComment/{id}
    defaults: { _controller: ClientBundle:Comment:deleteComment }
client_test:
    path:     /test
    defaults: { _controller: ClientBundle:Post:test }
ajout_ticket:
    path:     /addT
    defaults: { _controller: ClientBundle:Ticket:createTicket }

client_displayad:
    path:     /showAllAds
    defaults: { _controller: ClientBundle:Default:showAllAd }

client_moredetails:
    path:     /showMoreDetails{ad_id}
    defaults: { _controller: ClientBundle:Default:showMoreDetails }

client_addFav:
    path:     /addFav/{id}
    defaults: { _controller: ClientBundle:Default:AddFav }

client_showMyFavAds:
    path:     /showMyFavAds
    defaults: { _controller: ClientBundle:Default:showMyFavAds }

client_deleteFavAds:
    path:     /deleteFavAds/{adFav_id}
    defaults: { _controller: ClientBundle:Default:deleteFavAds }
client_showRating:
    path:     /showRating/{id}
    defaults: { _controller: ClientBundle:AskService:showRating }
client_rating:
    path:     /rating
    defaults: { _controller: ClientBundle:AskService:Rating }
    methods:  POST

client_mobiledisplay:
    path:     /displayMobile
    defaults: { _controller: ClientBundle:Mobile:displayMobile }

client_mobileAddAskService:
    path:     /addAskService
    defaults: { _controller: ClientBundle:Mobile:addAskService }
client_ajoutcommob:
  path:     /ajoutmob
  defaults: { _controller: ClientBundle:Postcommobile:ajoutercomMobile }

client_affichcommob:
  path:     /affichcommob/{id}
  defaults: { _controller: ClientBundle:Commentmobile:affichercomMobile }
client_ajoutmob:
  path:     /ajoutmob
  defaults: { _controller: ClientBundle:Postmobile:ajouterMobile }

client_affichmob:
  path:     /affichmob
  defaults: { _controller: ClientBundle:Postmobile:afficherMobile }
client_isAuth:
  path:     /login/{username}/{password}
  defaults: { _controller: ClientBundle:Mobile:login }
client_mobiledisplayAds:
  path:     /displayMobileAds
  defaults: { _controller: ClientBundle:MobileAds:displayMobileAds }
client_mobilefavorite:
    path:     /favorite
    defaults: { _controller: ClientBundle:MobileAds:favorite }
client_mobileshowfavorite:
    path:     /showFavorite/{idUser}
    defaults: { _controller: ClientBundle:MobileAds:showFavorite }
category_affichmob:
    path:     /categorymob
    defaults: { _controller: ClientBundle:Categorymobile:afficherMobileCat }
service_affichmob:
    path:     /servicemob/{id}
    defaults: { _controller: ClientBundle:Categorymobile:afficheServiceMobile }
service_proposermob:
    path:     /propsemob
    defaults: { _controller: ClientBundle:Categorymobile:AddPropositionMobile }
service_affichtick:
    path:     /ticket/all
    defaults: { _controller: ClientBundle:MobileTicket:afficherMobile}
service_addtick:
    path:     /ticket/add
    defaults: { _controller: ClientBundle:MobileTicket:ajouterMobile }
service_affichtickone:
    path:     /ticket/{id}
    defaults: { _controller: ClientBundle:MobileTicket:showjsonticket }
service_affichcateg:
  path:     /categ/all
  defaults: { _controller: ClientBundle:MobileCategoryt:afficherMobile}
service_addcateg:
  path:     /categ/add
  defaults: { _controller: ClientBundle:MobileCategoryt:ajouterMobile }
service_affichcategone:
  path:     /categ/{id}
  defaults: { _controller: ClientBundle:MobileCategoryt:showjsoncategoryt }
service_deletecateg:
  path:     /categ/delete/{id}
  defaults: { _controller: ClientBundle:MobileCategoryt:delete }
service_deleteticket:
  path:     /ticket/delete/{id}
  defaults: { _controller: ClientBundle:MobileTicket:delete }
client_ajouttcommob:
  path:     /ajoutcomment/{cnt}/{id}
  defaults: { _controller: ClientBundle:Commentmobile:ajoutercomMobile }
client_mobiledeleteFavAds:
  path:     /deleteFavorie/{id}
  defaults: { _controller: ClientBundle:MobileAds:deleteAdFav }
client_mobilechekFavAds:
  path:     /check/{id}
  defaults: { _controller: ClientBundle:MobileAds:check }
provider_showAdmobile:
  path:  /showMyAdsMobile/{idUser}
  defaults: { _controller: ClientBundle:MobileAds:showMyAds }
provider_mobiledeleteAds:
  path:     /deleteAdsProv/{id}
  defaults: { _controller: ClientBundle:MobileAds:deleteAdProv }